In [19]:
def sumLargestNumbers(iterable):
    if len(iterable) > 1:
        sorted_iterable = iterable
        sorted_iterable.sort()
        sorted_iterable[-1]
        return sorted_iterable[-1] + sorted_iterable[-2]
    else:
        return iterable


print(sumLargestNumbers([1, 10]))
print(sumLargestNumbers([1, 2, 3]))
print(sumLargestNumbers([10, 4, 34, 6, 92, 2]))
    
    

11
5
126


In [29]:
def conditionalSum(values, condition):
    solution = 0
    if condition == 'odd':
        for i in range(len(values)):
            if values[i] % 2 != 0:
                solution += values[i]
            else:
                continue
    elif condition == 'even':
        for i in range(len(values)):
            if values[i] % 2 == 0:
                solution += values[i]
            else:
                continue
    return solution
                
print(conditionalSum([1, 2, 3, 4, 5], "even"))
print(conditionalSum([1, 2, 3, 4, 5], "odd"))
print(conditionalSum([13, 88, 12, 44, 99], "even"))
print(conditionalSum([], "odd"))

6
9
144
0


In [35]:
def numberOfVowels(data):
    vowels = ['a','e','i','o','u']
    solution = 0
    for i in data:
        if i in vowels:
            solution += 1
        else:
            continue
    return solution
        

print(numberOfVowels("orange"))
print(numberOfVowels("lighthouse labs"))
print(numberOfVowels("aeiou"))

3
5
5


In [83]:
def instructorWithLongestName(instructors):

    return max(instructors, key=lambda d:len(d['name']))
        
print(instructorWithLongestName([
  {"name": "Samuel", "course": "iOS"},
  {"name": "Jeremiah", "course": "Data"},
  {"name": "Ophilia", "course": "Web"},
  {"name": "Donald", "course": "Web"}
]))
print(instructorWithLongestName([
  {"name": "Matthew", "course": "Data"},
  {"name": "David", "course": "iOS"},
  {"name": "Domascus", "course": "Web"}
]))

{'name': 'Jeremiah', 'course': 'Data'}
{'name': 'Domascus', 'course': 'Web'}


In [131]:
def urlEncode(text):
    url = ""
    #checking for spaces
    strip_text = text.rstrip().lstrip()
    for i in range(len(strip_text)):
        if strip_text[i] == ' ':
            url += '%20'
        else:
            url += strip_text[i]
    return url
        
print(urlEncode("Lighthouse Labs"))
print(urlEncode(" Lighthouse Labs  "))
print(urlEncode("blue is greener than purple for sure"))

Lighthouse%20Labs
Lighthouse%20Labs
blue%20is%20greener%20than%20purple%20for%20sure


In [78]:
def whereCanIPark(spots, vehicle):
    solution = []
    y = 0
    if vehicle == 'motorcycle':
        lookingfor = ['M', 'S', 'R']
    elif vehicle == 'small':
        lookingfor = ['S', 'R']
    else:
        lookingfor = ['R']
    
    for v in range(len(lookingfor)):
        for x in range(len(spots)):
            if lookingfor[v] in spots[x]:
                solution.append(spots[x].index(lookingfor[v]))
                solution.append(y)
                return solution
            elif y == len(spots)-1:
                return False
            else:
                y += 1
                continuea

print(whereCanIPark(
  [
    # COLUMNS ARE X
    # 0    1    2    3    4    5
    ['s', 's', 's', 'S', 'R', 'M'], # 0 ROWS ARE Y
    ['s', 'M', 's', 'S', 'r', 'M'], # 1
    ['s', 'M', 's', 'S', 'r', 'm'], # 2
    ['S', 'r', 's', 'm', 'r', 'M'], # 3
    ['S', 'r', 's', 'm', 'r', 'M'], # 4
    ['S', 'r', 'S', 'M', 'M', 'S']  # 5
  ],
  'regular'
))

print(whereCanIPark(
  [
    ['M', 'M', 'M', 'M'],
    ['M', 's', 'M', 'M'],
    ['M', 'M', 'M', 'M'],
    ['M', 'M', 'r', 'M']
  ],
  'small'
))

print(whereCanIPark(
  [
    ['s', 's', 's', 's', 's', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['S', 'r', 's', 'm', 'r', 's'],
    ['S', 'r', 's', 'm', 'R', 's'],
    ['S', 'r', 'S', 'M', 'm', 'S']
  ],
  'motorcycle'
))

[4, 0]
False
[3, 5]


In [31]:
from collections import Counter

def checkAir(samples, threshold):
    samples_count = Counter(samples)
    if samples_count['dirty'] / len(samples) > threshold:
        return 'Polluted'
    else:
        return 'Clean'
    
print(checkAir(
  ['clean', 'clean', 'dirty', 'clean', 'dirty', 'clean', 'clean', 'dirty', 'clean', 'dirty'],
  0.3
))

print(checkAir(
  ['dirty', 'dirty', 'dirty', 'dirty', 'clean'],
  0.25
))

print(checkAir(
  ['clean', 'dirty', 'clean', 'dirty', 'clean', 'dirty', 'clean'],
  0.9
))


Polluted
Polluted
Clean


The input data for this exercise will be a nested list (a list of lists), where each sub-list will have two numeric values. For example:

[[1, 2], [2, 3]]
The first will be the value to repeat, the second will be the amount of times to repeat that value.

Instruction
Create a function named repeatNumbers that will return a string with each of the given values repeated the appropriate number of times. If there are multiple sets of values each set should be separated by a comma. If there is only one set of values then you should omit the comma.

In [35]:
def repeatNumbers(lists):
    # create list of strings to be joined later
    solution_list = []
    for i in range(len(lists)):
        string = str(lists[i][0])
        n = lists[i][1]
        strings = string * n 
        solution_list.append(str(strings))
    # put strings together and return
    solution_string = "".join(solution_list)        
    return str(solution_string)

print(repeatNumbers([[1, 10]]))
print(repeatNumbers([[1, 2], [2, 3]]))
print(repeatNumbers([[10, 4], [34, 6], [92, 2]]))

1111111111
11222
101010103434343434349292


In [51]:
def repeatNumbers(lists):
    # create list of strings to be joined later
    solution_list = []
    for i in range(len(lists)):
        string = str(lists[i][0])
        n = lists[i][1]
        strings = string * n 
        solution_list.append(str(strings))
    solution_string = ", ".join(solution_list) 
    return solution_string

print(repeatNumbers([[1, 10]]))
print(repeatNumbers([[1, 2], [2, 3]]))
print(repeatNumbers([[10, 4], [34, 6], [92, 2]]))

1111111111
11, 222
10101010, 343434343434, 9292


##### Create a function named multiplicationTable that receives a number maxValue as input and creates a square multiplication table where maxValue is the largest value in the table.

In [22]:
import numpy as np

def multiplicationTable(maxValue):
    mult = np.arange(1, maxValue+1)
    mult_table = mult * mult[:, None]
    return str(mult_table)

print(multiplicationTable(1))
print(multiplicationTable(5))
print(multiplicationTable(10))

[[1]]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
