The Basics

In [2]:
import numpy as np

In [19]:
#The basics
#one dimensional array
a = np.array([1,2,3], dtype='int64')
print(a)

[1 2 3]


In [3]:
#2D
b = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
print(b)

[[9. 8. 7.]
 [1. 2. 3.]]


In [4]:
#Get Dimension
b.ndim

2

In [6]:
#Get Shape
b.shape

(2, 3)

In [17]:
#Get Type
a.dtype

dtype('int16')

In [23]:
#Get Size
a.itemsize
b.itemsize

8

In [22]:
#Get total size
a.nbytes

24

Accessing / Changing specific elements, rows, columns, etc.

In [25]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
# Get a specific element [r, c]
a[1, 5]

13

In [27]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
# Get a specific column
a[:, 2] 

array([ 3, 10])

In [29]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2] 

array([2, 4, 6])

In [33]:
# Changing elements in an array
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-d example

In [34]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [37]:
# Get a specific element (work outside in)
b[0,1,0]

3

In [42]:
# Change a range of elements (keep same dimension)
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


Initialize different arrays

In [45]:
# All 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [47]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [51]:
#Any other number
np.full((2,2), 99, dtype='float64')

array([[99., 99.],
       [99., 99.]])

In [54]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [57]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.06209445, 0.33578841, 0.98884016],
        [0.82525619, 0.08050023, 0.94923151]],

       [[0.58239822, 0.75224117, 0.91095492],
        [0.17545449, 0.24362643, 0.93532214]],

       [[0.09629906, 0.62184739, 0.18308003],
        [0.89384952, 0.50516685, 0.98693335]],

       [[0.4842901 , 0.74669171, 0.37107063],
        [0.49624901, 0.11244533, 0.26036275]]])

In [61]:
# Copy a shape while generating random decimal numbers
np.random.random_sample(a.shape)

array([[0.94893619, 0.9469319 , 0.21783182, 0.2362407 , 0.59108083,
        0.33492413, 0.99274218],
       [0.95751691, 0.00655206, 0.85960766, 0.01161641, 0.24356852,
        0.40858121, 0.08300353]])

In [69]:
# Random integer values
np.random.randint(-4, 8, size=(3,3))

array([[ 3,  1, -3],
       [ 3,  5,  3],
       [ 6,  0,  5]])

In [70]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

##### Be caregful when copying arrays!!!

In [88]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [90]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)
print(a)

[100   2   3]
[1 2 3]


Mathematics

In [5]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [99]:
a += 2
a

array([5, 6, 7, 8])

In [94]:
a - 2

array([-1,  0,  1,  2])

In [95]:
a * 2

array([2, 4, 6, 8])

In [96]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [6]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [7]:
a ** 2

array([ 1,  4,  9, 16])

In [8]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

######Linear Algebra

In [13]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [15]:
# Find the determinate
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [16]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.min(stats, axis = 1)

array([1, 4])

In [2]:
np.max(stats, axis=0)

NameError: name 'np' is not defined

In [20]:
np.sum(stats, axis=0)

array([5, 7, 9])

######Reorganizing Arrays

In [26]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [28]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
# Horizontal Stacks

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [39]:
### miscellaneous
### load data from file
filedata = np.gengromtxt('data.txt', delimeter=',')
filedata = filedata.astype('in32')

AttributeError: module 'numpy' has no attribute 'gengromtxt'

### Boolean Masking and Advanced Indexing

In [40]:
filedata > 50

NameError: name 'filedata' is not defined

In [41]:
filedata[filedata > 50]

NameError: name 'filedata' is not defined

In [43]:
## You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [45]:
np.any(filedata > 50, axis =0)

NameError: name 'filedata' is not defined

In [46]:
np.all(filedata . 50, axis=0)

SyntaxError: invalid syntax (1477504865.py, line 1)

In [48]:
(~(filedata > 50) & (filedata < 100))

NameError: name 'filedata' is not defined

In [ ]:
[[0,4,5],3:5]