# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [5]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [50]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [28]:
a = np.array(range(10))
print(a)
a = a[::-1]
a

[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [52]:
a = np.array([[range(0,9)],[range(0,9)], [range(0,9)]])
print(a)

[[[0 1 2 3 4 5 6 7 8]]

 [[0 1 2 3 4 5 6 7 8]]

 [[0 1 2 3 4 5 6 7 8]]]


#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [44]:
a = np.array([1,2,0,0,4,0])
np.where(a != 0)

(array([0, 1, 4]),)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [47]:
a = np.random.randint(0,10, size=(3,3,3))
a

array([[[5, 6, 3],
        [5, 8, 3],
        [6, 8, 0]],

       [[7, 0, 3],
        [9, 7, 2],
        [0, 1, 3]],

       [[1, 2, 1],
        [7, 4, 5],
        [2, 8, 8]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [71]:
a = np.random.randint(0,1000, size=(10,10))
print(np.min(a))
print(np.max(a))

8
998


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [73]:
a = np.random.randint(0,100, size=(30))
np.mean(a)

52.0

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [107]:
a = np.zeros((6,6))
print(a)
b = np.ones((4,4))
print(b)
a[1:-1,1:-1] = b
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [113]:
# make array
a = np.ones((5,5))
a
# add border of 0's with np.pad
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan # nan
np.nan == np.nan # False
np.inf > np.nan # False
np.nan - np.nan # nan
np.nan in set([np.nan]) # True
0.3 == 3 * 0.1 # False
```

In [124]:
### All boolean with nan returns false, all algebra returns nan

nan

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [11]:
to_modify = np.zeros((5,5), int)
print(to_modify)
# create replacement for original matrix
replacement = np.zeros((4,4))
np.fill_diagonal(replacement,[1,2,3,4])
print(replacement)
# replace values in original matrix
to_modify[1:5,0:4] = replacement
print(to_modify)

# indexes = [[1,0],[2,1],[3,2],[4,3]]




[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [33]:
an_array = np.zeros((6,7,8))
where_z = 7 * 8
z = 2

x = 100 - y
print(x)
print(x / 7)
# an_array[1,5,2] is the index of 100

44
6.285714285714286


#### 16. Normalize a 5x5 random matrix (★☆☆)

In [48]:
random_array = np.random.random((5,5))
print(random_array)
random_max, random_min = random_array.max(), random_array.min()
normalized_array = (random_array - random_min)/(random_max - random_min)
print(normalized_array)


[[0.02238906 0.07284908 0.04995848 0.83454947 0.12197595]
 [0.26979028 0.12131594 0.06141963 0.62545801 0.39348373]
 [0.17216396 0.13541516 0.98562974 0.95117399 0.93777226]
 [0.32864524 0.82014516 0.88533899 0.42893278 0.16255401]
 [0.81120846 0.45967129 0.56488143 0.91579186 0.81891242]]
[[0.         0.05238568 0.02862153 0.84315418 0.10338733]
 [0.25684257 0.10270214 0.04052006 0.62608334 0.38525643]
 [0.15549063 0.11733941 1.         0.96422934 0.95031617]
 [0.31794357 0.82820017 0.89588194 0.42205829 0.14551394]
 [0.81892243 0.45396985 0.56319504 0.92749695 0.82692039]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [53]:
arr = np.arange(10)
arr

x = (arr > 3) & (arr < 8)
arr[x] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 18. How to round away from zero a float array ? (★☆☆)

In [60]:
arr = np.random.random((20))
arr

arr = np.round(arr)
arr

array([0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1.,
       1., 1., 0.])

#### 19. Find common values between two arrays? (★☆☆)

In [8]:
arr1 = [*range(0,100,5)]
arr2 = [*range(0,100,10)]
solve = np.intersect1d(arr1,arr2)
print(solve)

[ 0 10 20 30 40 50 60 70 80 90]


#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [5]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\lapen\AppData\Local\Temp/ipykernel_9672/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [10]:
arr1 = [*range(10)]
arr1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [19]:
solve = np.linspace(0,1,12,endpoint=True)[1:-1]
solve

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 23. Create a random vector of size 10 and sort it (★★☆)

In [24]:
# generate random vector
rvector = np.random.randint(0,100,size=(10))

# sort the vector
svector = np.sort(rvector)
svector

array([ 7, 20, 35, 41, 44, 50, 50, 71, 79, 94])

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [31]:
# generate arrays
arr1 = np.random.randint(0,100,5)
arr2 = np.random.randint(0,100,5)

# Check if arrays equal each other
array_equal = np.allclose(arr1,arr2)
array_equal

False

#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [40]:
vector = np.random.random(10)
# use np.where to find the index of a given value, using .amax to find the max value
vector[np.where(vector == np.amax(vector))] = 0
vector

array([0.32762281, 0.06859351, 0.        , 0.40665569, 0.43368649,
       0.12247629, 0.3649854 , 0.5380293 , 0.49906195, 0.06630196])

#### 26. Find the closest value to random element in a vector? (★★☆)

In [44]:
def find_nearest(array, value):
        #create an array
        array = np.asarray(array)
        # the index is equal to the object with the shortest difference from the value. array - value gives the distance, argmin() returns the smallest difference
        idx = (np.abs(array - value)).argmin()
        return array[idx]

array = np.random.random(10)
print(array)

value = 0.5

print(find_nearest(array, value))

[0.39410193 0.20785941 0.53279083 0.47788865 0.29000915 0.13123248
 0.20260216 0.20815984 0.56566777 0.69245907]
0.4778886463962322


#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [54]:
arr = np.array([0.1,0.2,0.3,0.4])
print(arr)
arr = arr.astype('int32')
print(arr)

[0.1 0.2 0.3 0.4]
[0 0 0 0]


#### 28. Sort an array by the nth column? (★★☆)

In [59]:
# generate random vector
rarray = np.random.randint(0,100,size=(10,10))
print(rvector)
# sort array by column

svecto


SyntaxError: positional argument follows keyword argument (Temp/ipykernel_9672/3240511406.py, line 5)

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 31. Swap two rows of an array? (★★★)

#### 32. How to negate a boolean value inside an array? (★★★)

#### 33. Find the most frequent value in an array?

#### 34. Get the n largest values of an array (★★★)

#### 35. Extract unique rows from a two dimensional array? (★★★)